function f = f_function(ALPHAT,FxF,FxM,FxR,FyF,FyM,FyR,PHI,PSI,VT,a,b,c,d,dPHI,dPSI,deltaf,deltam,deltar,e,mS,mT)
%F_FUNCTION
%    F = F_FUNCTION(ALPHAT,FXF,FXM,FXR,FYF,FYM,FYR,PHI,PSI,VT,A,B,C,D,DPHI,DPSI,DELTAF,DELTAM,DELTAR,E,MS,MT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Dec-2020 02:16:31

%Version: 1.1
t2 = cos(ALPHAT);
t3 = cos(PSI);
t4 = sin(PHI);
t5 = sin(PSI);
t6 = cos(deltam);
t7 = sin(deltam);
t8 = PSI+deltaf;
t9 = PSI+deltar;
t10 = dPHI.^2;
t11 = dPSI.^2;
t12 = ALPHAT+PHI;
t13 = ALPHAT+PSI;
t21 = -PHI;
t22 = -PSI;
t23 = -deltam;
t14 = cos(t12);
t15 = cos(t13);
t16 = sin(t13);
t17 = cos(t8);
t18 = cos(t9);
t19 = sin(t8);
t20 = sin(t9);
t24 = FyM.*d.*t6;
t25 = FyM.*e.*t6;
t26 = FxM.*d.*t7;
t27 = FxM.*e.*t7;
t28 = PHI+t22;
t29 = PHI+t23;
t31 = PSI+deltam+t21;
t30 = cos(t28);
t32 = sin(t28);
t33 = cos(t29);
t34 = sin(t29);
t35 = cos(t31);
t36 = sin(t31);
t37 = VT.*d.*dPSI.*mS.*t14;
f = [VT.*t15;VT.*t16;dPSI;dPHI;FxF.*t17+FxM.*t35+FxR.*t18-FyF.*t19-FyM.*t36-FyR.*t20-b.*mS.*t3.*t11-c.*mS.*t3.*t11-d.*mS.*t10.*t30-d.*mS.*t11.*t30+VT.*dPSI.*mS.*t16+VT.*dPSI.*mT.*t16+d.*dPHI.*dPSI.*mS.*t30.*2.0;FxF.*t19+FxM.*t36+FxR.*t20+FyF.*t17+FyM.*t35+FyR.*t18-b.*mS.*t5.*t11-c.*mS.*t5.*t11+d.*mS.*t10.*t32+d.*mS.*t11.*t32-VT.*dPSI.*mS.*t15-VT.*dPSI.*mT.*t15-d.*dPHI.*dPSI.*mS.*t32.*2.0;-t24-t25-t26-t27+t37+FxM.*b.*t34-FyM.*b.*t33+FxM.*c.*t34-FyM.*c.*t33+FyF.*a.*cos(deltaf)-FyR.*b.*cos(deltar)+FxF.*a.*sin(deltaf)-FxR.*b.*sin(deltar)+VT.*b.*dPSI.*mS.*t2+VT.*c.*dPSI.*mS.*t2-b.*d.*mS.*t4.*t10-c.*d.*mS.*t4.*t10+b.*d.*dPHI.*dPSI.*mS.*t4.*2.0+c.*d.*dPHI.*dPSI.*mS.*t4.*2.0;t24+t25+t26+t27-t37-b.*d.*mS.*t4.*t11-c.*d.*mS.*t4.*t11];
