function M = M_function(ALPHAT,IS,IT,PHI,PSI,VT,b,c,d,mS,mT)
%M_FUNCTION
%    M = M_FUNCTION(ALPHAT,IS,IT,PHI,PSI,VT,B,C,D,MS,MT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Dec-2020 02:16:31

%Version: 1.1
t2 = cos(ALPHAT);
t3 = cos(PHI);
t4 = sin(ALPHAT);
t5 = b+c;
t6 = mS+mT;
t7 = d.^2;
t8 = ALPHAT+PHI;
t9 = ALPHAT+PSI;
t14 = -IS;
t15 = -PSI;
t10 = cos(t8);
t11 = cos(t9);
t12 = sin(t8);
t13 = sin(t9);
t16 = mS.*t7;
t17 = b.*d.*mS.*t3;
t18 = c.*d.*mS.*t3;
t19 = PHI+t15;
t20 = -t16;
t21 = cos(t19);
t22 = sin(t19);
t23 = -t17;
t24 = -t18;
t25 = t14+t20+t23+t24;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t6.*t11,t6.*t13,-mS.*(b.*t4+c.*t4+d.*t12),d.*mS.*t12,0.0,0.0,0.0,0.0,-VT.*t6.*t13,VT.*t6.*t11,-VT.*mS.*(b.*t2+c.*t2+d.*t10),VT.*d.*mS.*t10,0.0,0.0,0.0,0.0,mS.*(d.*t22.*2.0-t5.*sin(PSI).*2.0).*(-1.0./2.0),mS.*(d.*t21.*2.0+t5.*cos(PSI).*2.0).*(-1.0./2.0),IS+IT+t16+t17.*2.0+t18.*2.0+b.^2.*mS+c.^2.*mS+b.*c.*mS.*2.0,t25,0.0,0.0,0.0,0.0,d.*mS.*t22,d.*mS.*t21,t25,IS+t16],[8,8]);
